### ISSUE TITLE
License

### ISSUE THREAD

**Issue by 6r1d** [Saegor/acratone#1]
Hello. I like your polyphony code, it is a useful reference to learn from, thank you for that.

Apparently, it's not allowed to use [code from a projects with no license](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license).

I was playing with [libsound.io](http://libsound.io/) and made [this little Gist](https://gist.github.com/6r1d/417ac2090693a42a5c6f83ab43079ba9/) using a part of it, mainly as a simple note on using polyphony for the future.
Could you add some kind of a permissive license (good examples are MIT and BSD) so others can use your code, please? WTFPL as in isomap is awesome, too, although I heard it might be less valid in some countries. :-)

Alternatively, if you aren't happy about it, I'll rewrite my gist.

**Comment by Saegor** [comment]
done, i've licensed it under MIT :-)

**Comment by 6r1d** [comment]
Thanks a lot!
